service: lambda-bash

frameworkVersion: '2'

provider:
  name: aws
  region: ap-northeast-1

functions:
  hello:
    image: "${file(./image-uri.txt)}"
    events:
      - http:
          path: hello
          method: get